sidebar:
  menu:
    personal_homepage: '[btn.personal_homepage](https://www.cubik65536.top/)'
    home1: '[btn.blog_home](/)'
    post1: '[btn.blog](/blog/)'
    wiki1: '[btn.wiki](/wiki/)'
    notes1: '[btn.notes](/notes/)'
    more1: '[btn.more](/more/)'
    friends1: '[btn.friends](/friends/)'
footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/Rush/Font-Awesome-SVG-PNG@master/white/svg/github.svg"/>'
      url: https://github.com/Cubik65536
    - icon: '<img src="https://img.cubik65536.top/mail-bulk-solid.svg"/>'
      url: mailto:cubik65536@cubik65536.top
    - icon: '<img src="https://cdn.jsdelivr.net/gh/Rush/Font-Awesome-SVG-PNG@master/white/svg/comments.svg"/>'
      url: /more/#comments
  sitemap:
    '主页':
      - '[简介](/)'
      - '[近期日程](/#近期日程)'
      - '[兴趣爱好](/#兴趣爱好)'
    '博客':
      - '[近期发布](/blog/)'
      - '[分类](/categories/)'
      - '[标签](/tags/)'
      - '[归档](/archives/)'
    'Wiki':
#      - '[所有项目](/wiki/)'
      - '[便签](/notes/)'
    '社交':
      - '[个人主页](https://www.cubik65536.top/)'
      - '[友链](/friends/)'
      - '[留言板](/more#comments)'
    '联系我们':
      - '[Email](mailto:cubik65536@cubik65536.top)'
      - '[GitHub](https://github.com/Cubik65536)'

#  source: '[GitHub](https://github.com/Cubik65536/Cubik65536.github.io/)'
comments:
  service: utterances # utterances
  utterances:
    repo: Cubik65536/blog-comments