######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)'
  menu:
    home: '[btn.home](/)'
    post: '[btn.blog](/posts/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[btn.notes](/notes/)'
    friends: '[btn.friends](/friends/)'
  # Sidebar widgets
  widgets:
    index: welcome, search, recent, timeline # for home/wiki/categories/tags/archives/404 pages
    page: welcome, search, toc # for pages using 'layout:page'
    post: toc, search, ghrepo, ghissues # for pages using 'layout:post'
    wiki: search, ghrepo, toc, ghissues, related # for pages using 'layout:wiki'

######## Index ########
post-index: # 近期发布 分类 标签 归档 and ...
  '近期动态': /timeline/ # 这里填写的链接要与对应页面一致，否则可能无法正确高亮

######## Article ########
article:
  # 文章许可协议
  license: '本文采用 [署名 - 非商业性使用 - 相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share: [email, link]

search:
  service: local_search # local_search, todo...
  local_search:
    field: all # post, page, all
    path: /search.json
    content: true

######## Comments ########
comments:
  service: waline
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL: https://waline.cubik65536.top
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: true
    # Custom emoji
    emoji:
      - https://unpkg.com/@waline/emojis@1.0.1/weibo
      - https://unpkg.com/@waline/emojis@1.0.1/alus
      - https://unpkg.com/@waline/emojis@1.0.1/bilibili
      - https://unpkg.com/@waline/emojis@1.0.1/qq
      - https://unpkg.com/@waline/emojis@1.0.1/tieba
      - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
    # Comment infomation, valid meta are nick, mail and link
    meta:
      - nick
      - mail
      - link
    # Set required meta field, e.g.: [nick] | [nick, mail]
    requiredMeta:
      - nick
      - mail
    # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    lang: zh-CN
    # Whether enable login, can choose from 'enable', 'disable' and 'force'
    login: force
    # comment per page
    pageSize: 10

######## Footer ########
footer:
  since: 2020
  social:
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/brands/github.svg" />'
      url: https://github.com/Cubik65536
      title: 'GitHub (@Cubik65536)'
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/brands/gitlab.svg"/>'
      url: https://gitlab.com/Cubik65536
      title: 'GitLab (@Cubik65536)'
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/brands/bilibili.svg"/>'
      url: https://space.bilibili.com/439205819
      title: '哔哩哔哩 (@Cubik65536)'
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/brands/telegram.svg"/>'
      url: https://t.me/cubiksteleblog
      title: 'Telegram (Cubik''s Teleblog)'
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/regular/envelopes-bulk.svg"/>'
      url: mailto:me@cubik65536.top
      title: '向我发送邮件'
  largesocial:
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/light/fingerprint.svg" />'
      url: https://keys.openpgp.org/vks/v1/by-fingerprint/1B388B7AA395A248F436244FFFA7DB1132238420
      title: '从 keys.openpgp.org 下载 PGP 公钥'
      description: '我的 PGP 公钥'
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/light/bullseye-pointer.svg" />'
      url: https://foreverblog.cn/go.html
      title: '穿梭虫洞 - 随机访问十年之约友链博客'
      description: '虫洞 | WORMHOLE'
    - icon: '<img src="https://fapro6.cubik65536.top/svgs/light/train.svg" />'
      url: https://www.travellings.cn/go.html
      title: '开往 - 友链接力'
      description: '开往 | Travelling'
  picturesocial:
    - url: https://www.foreverblog.cn/blog/2992.html
      image: https://img.foreverblog.cn/logo_en_default.png
      description: '【CUBIK 的小站】十年之约'
  sitemap:
    '主页':
      - '[关于](/)'
      - '[联系我](/contact-me/)'
      - '[我的 PGP](/my-pgp/)'
    '博客':
      - '[近期发布](/posts/)'
      - '[分类](/categories/)'
      - '[标签](/tags/)'
      - '[归档](/archives/)'
      - '[知识库](/wiki/)'
      - '[笔记](/notes/)'
      - '[网址收藏](/bookmarks/)'
      - '[Git 提交信息格式](/commit-message-conventions/)'
    '社交':
      - '[友链](/friends/)'
      - '[哔哩哔哩](https://space.bilibili.com/439205819)'
      - '[Telegram 频道](https://t.me/cubiksteleblog)'
      - '[虫洞 | WORMHOLE](https://foreverblog.cn/go.html)'
      - '[开往 | Travelling](https://www.travellings.cn/go.html)'
    '联系我':
      - '[联系我 (详细信息页)](/contact-me/)'
      - '[Email](mailto:me@cubik65536.top)'
      - '[Email (PGP 签名的)](mailto:me@enc.cubik65536.top)'
      - '[GitHub](https://github.com/Cubik65536)'
      - '[GitLab](https://gitlab.com/Cubik65536)'
      - '[keys.openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/1B388B7AA395A248F436244FFFA7DB1132238420)'
  content: |
    本博客由 [Hexo](https://hexo.io/) & [Hexo Theme Stellar](https://xaoxuu.com/wiki/stellar/) 强力驱动，您可以在 [GitHub](https://github.com/Cubik65536/cubik-website/) 找到本站源码。
    Copyright © 2020-2023 [@Cubik65536](https://cubik65536.top) 保留所有权利。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 许可协议，转载请注明出处。

######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true

######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
  jquery: https://gcore.jsdelivr.net/npm/jquery@3.6.2/dist/jquery.min.js

  # stellar api
  stellar:
    sites: /js/plugins/sites.js
    friends: /js/plugins/friends.js
    ghinfo: /js/plugins/ghinfo.js
    timeline: /js/plugins/timeline.js
    linkcard: /js/plugins/linkcard.js
    fcircle: /js/plugins/fcircle.js
    weibo: /js/plugins/weibo.js

  marked: https://cdn.bootcdn.net/ajax/libs/marked/4.0.18/marked.min.js
  
  ## optional plugins #
  # MathJax
  # 需在 Markdown 文件开头加入 mathjax: true
  # npm uninstall hexo-renderer-marked --save 
  # npm uninstall hexo-renderer-pandoc --save
  # npm install hexo-renderer-kramed --save
  mathjax:
    enable: true
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML

style:
  font-size:
    root: 16px
    body: .9375rem # 15px
    code: 85% # 14px
    codeblock: 0.8125rem # 13px
  font-family:
    logo: '"ProFont For Powerline", "Smiley Sans", "LXGW WenKai Screen", "Apple Color Emoji", "Source Han Serif", system-ui, -apple-system, sans-serif'
    body: '"ProFont For Powerline", "Smiley Sans", "LXGW WenKai Screen", "Apple Color Emoji", "Source Han Serif", system-ui, -apple-system, sans-serif'
    code: '"ProFont For Powerline", "Smiley Sans", "LXGW WenKai Screen", "Apple Color Emoji", "Source Han Serif", system-ui, -apple-system, monospace, sans-serif'
    codeblock: '"ProFont For Powerline", "Smiley Sans", "LXGW WenKai Screen", "Apple Color Emoji", "Source Han Serif", system-ui, -apple-system, monospace, sans-serif'
  color:
    # 动态颜色（会根据明暗主题重设明度值，只用关心色相和饱和度即可）
    background: 'hsl(212 16% 98%)' # 浅色背景颜色
    block: 'hsl(212 8% 95%)' # 块背景颜色
    code: 'hsl(14 100% 48%)' # 行内代码颜色
    text: 'hsl(0 0% 20%)' # 文本颜色
    # 主题色配置（不会根据明暗动态调整，请设置为通用的颜色）
    theme: '#57728B' # 主题色
    accent: '#63829E' # 强调色
    link: 'hsl(207 90% 54%)' # 超链接颜色
    button: 'hsl(192 98% 55%)' # 按钮颜色
    hover: '#63829E' # 按钮高亮颜色
