sidebar:
  menu:
    home: '[btn.home](/)'
    post: '[btn.blog](/blog/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[btn.notes](/notes/)'
    more: '[btn.more](/more/)'
    friends: '[btn.friends](/friends/)'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/brands/github.svg"/>'
      url: https://github.com/Cubik65536
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/brands/gitlab.svg"/>'
      url: https://gitlab.com/Cubik65536
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/brands/bilibili.svg"/>'
      url: https://space.bilibili.com/439205819
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/brands/telegram.svg"/>'
      url: https://t.me/cubiksteleblog
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/solid/envelopes-bulk.svg"/>'
      url: mailto:me@cubik65536.top
    - icon: '<img src="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/svgs/solid/comments.svg"/>'
      url: /more/#comments
  sitemap:
    '主页':
      - '[简介](/)'
      - '[近期日程](/#近期日程)'
      - '[兴趣爱好](/#兴趣爱好)'
    '博客':
      - '[近期发布](/blog/)'
      - '[分类](/categories/)'
      - '[标签](/tags/)'
      - '[归档](/archives/)'
    '知识库':
      - '[知识库](/wiki/)'
      - '[便签](/notes/)'
    '社交':
      - '[友链](/friends/)'
      - '[哔哩哔哩](https://space.bilibili.com/439205819)'
      - '[Telegram 频道](https://t.me/cubiksteleblog)'
      - '[留言板](/more#comments)'
    '联系我们':
      - '[Email](mailto:me@cubik65536.top)'
      - '[GitHub](https://github.com/Cubik65536)'
      - '[GitLab](https://gitlab.com/Cubik65536)'

  source: '[GitHub](https://github.com/Cubik65536/cubik-website/)'

comments:
  service: utterances # utterances
  utterances:
    repo: Cubik65536/blog-comments

######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true
